const PHONEMES = {
"'bout": ['B', 'AW1', 'T'],
"'cause": ['K', 'AH0', 'Z'],
"'course": ['K', 'AO1', 'R', 'S'],
"'cuse": ['K', 'Y', 'UW1', 'Z'],
"'em": ['AH0', 'M'],
"'frisco": ['F', 'R', 'IH1', 'S', 'K', 'OW0'],
"'gain": ['G', 'EH1', 'N'],
"'kay": ['K', 'EY1'],
"'m": ['AH0', 'M'],
"'n": ['AH0', 'N'],
"'round": ['R', 'AW1', 'N', 'D'],
"'s": ['EH1', 'S'],
"'til": ['T', 'IH1', 'L'],
"'tis": ['T', 'IH1', 'Z'],
"'twas": ['T', 'W', 'AH1', 'Z'],
"a": ['AH0'],
"a's": ['EY1', 'Z'],
"aaa": ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1'],
"aaberg": ['AA1', 'B', 'ER0', 'G'],
"aachen": ['AA1', 'K', 'AH0', 'N'],
"aachener": ['AA1', 'K', 'AH0', 'N', 'ER0'],
"aaker": ['AA1', 'K', 'ER0'],
"aalborg": ['AO1', 'L', 'B', 'AO0', 'R', 'G', '#', 'place,', 'danish'],
"aalburg": ['AE1', 'L', 'B', 'ER0', 'G', '#', 'place,', 'dutch'],
"aalen": ['AE1', 'L', 'AH0', 'N', '#', 'place,', 'german'],
"aaliyah": ['AA2', 'L', 'IY1', 'AA2'],
"aalseth": ['AA1', 'L', 'S', 'EH0', 'TH'],
"aalsmeer": ['AA1', 'L', 'S', 'M', 'IH0', 'R', '#', 'place,', 'dutch'],
"aalto": ['AA1', 'L', 'T', 'OW2', '#', 'name,', 'finnish'],
"aamodt": ['AA1', 'M', 'AH0', 'T'],
"aancor": ['AA1', 'N', 'K', 'AO2', 'R'],
"aardema": ['AA0', 'R', 'D', 'EH1', 'M', 'AH0'],
"aardvark": ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K'],
"aardvarks": ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K', 'S'],
"aargh": ['AA1', 'R', 'G'],
"aarhus": ['AA2', 'HH', 'UW1', 'S'],
"aaron": ['EH1', 'R', 'AH0', 'N'],
"aaron's": ['EH1', 'R', 'AH0', 'N', 'Z'],
"aarons": ['EH1', 'R', 'AH0', 'N', 'Z'],
"aaronson": ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N'],
"aaronson's": ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'],
"aarti": ['AA1', 'R', 'T', 'IY2'],
"aase": ['AA1', 'S'],
"aasen": ['AA1', 'S', 'AH0', 'N'],
"ab": ['AE1', 'B'],
"aba": ['EY2', 'B', 'IY2', 'EY1'],
"ababa": ['AH0', 'B', 'AA1', 'B', 'AH0'],
"abacha": ['AE1', 'B', 'AH0', 'K', 'AH0'],
"aback": ['AH0', 'B', 'AE1', 'K'],
"abaco": ['AE1', 'B', 'AH0', 'K', 'OW2'],
"abacus": ['AE1', 'B', 'AH0', 'K', 'AH0', 'S'],
"abad": ['AH0', 'B', 'AA1', 'D'],
"abadaka": ['AH0', 'B', 'AE1', 'D', 'AH0', 'K', 'AH0'],
"abadi": ['AH0', 'B', 'AE1', 'D', 'IY0'],
"abadie": ['AH0', 'B', 'AE1', 'D', 'IY0'],
"abair": ['AH0', 'B', 'EH1', 'R'],
"abalkin": ['AH0', 'B', 'AA1', 'L', 'K', 'IH0', 'N'],
"abalone": ['AE2', 'B', 'AH0', 'L', 'OW1', 'N', 'IY0'],
"abalones": ['AE2', 'B', 'AH0', 'L', 'OW1', 'N', 'IY0', 'Z'],
"abalos": ['AA0', 'B', 'AA1', 'L', 'OW0', 'Z'],
"abandon": ['AH0', 'B', 'AE1', 'N', 'D', 'AH0', 'N'],
"abandoned": ['AH0', 'B', 'AE1', 'N', 'D', 'AH0', 'N', 'D'],
"abandoning": ['AH0', 'B', 'AE1', 'N', 'D', 'AH0', 'N', 'IH0', 'NG'],
"abandonment": ['AH0', 'B', 'AE1', 'N', 'D', 'AH0', 'N', 'M', 'AH0', 'N', 'T'],
"abandonments": ['AH0', 'B', 'AE1', 'N', 'D', 'AH0', 'N', 'M', 'AH0', 'N', 'T', 'S'],
"abandons": ['AH0', 'B', 'AE1', 'N', 'D', 'AH0', 'N', 'Z'],
"abanto": ['AH0', 'B', 'AE1', 'N', 'T', 'OW0'],
"abarca": ['AH0', 'B', 'AA1', 'R', 'K', 'AH0'],
"abare": ['AA0', 'B', 'AA1', 'R', 'IY0'],
"abascal": ['AE1', 'B', 'AH0', 'S', 'K', 'AH0', 'L'],
"abash": ['AH0', 'B', 'AE1', 'SH'],
"abashed": ['AH0', 'B', 'AE1', 'SH', 'T'],
"abasia": ['AH0', 'B', 'EY1', 'ZH', 'Y', 'AH0'],
"abate": ['AH0', 'B', 'EY1', 'T'],
"abated": ['AH0', 'B', 'EY1', 'T', 'IH0', 'D'],
"abatement": ['AH0', 'B', 'EY1', 'T', 'M', 'AH0', 'N', 'T'],
"abatements": ['AH0', 'B', 'EY1', 'T', 'M', 'AH0', 'N', 'T', 'S'],
"abates": ['AH0', 'B', 'EY1', 'T', 'S'],
"abating": ['AH0', 'B', 'EY1', 'T', 'IH0', 'NG'],
"abattoir": ['AE2', 'B', 'AH0', 'T', 'W', 'AA1', 'R'],
"abba": ['AE1', 'B', 'AH0'],
"abbado": ['AH0', 'B', 'AA1', 'D', 'OW0'],
"abbas": ['AH0', 'B', 'AA1', 'S'],
"abbasi": ['AA0', 'B', 'AA1', 'S', 'IY0'],
"abbate": ['AA1', 'B', 'EY0', 'T'],
"abbatiello": ['AA0', 'B', 'AA0', 'T', 'IY0', 'EH1', 'L', 'OW0'],
"abbe": ['AE1', 'B', 'IY0'],
"abbenhaus": ['AE1', 'B', 'AH0', 'N', 'HH', 'AW2', 'S'],
"abbett": ['AH0', 'B', 'EH1', 'T'],
"abbeville": ['AE1', 'B', 'V', 'IH0', 'L'],
"abbey": ['AE1', 'B', 'IY0'],
"abbey's": ['AE1', 'B', 'IY0', 'Z'],
"abbie": ['AE1', 'B', 'IY0'],
"abbitt": ['AE1', 'B', 'IH0', 'T'],
"abbot": ['AE1', 'B', 'AH0', 'T'],
"abbotstown": ['AE1', 'B', 'AH0', 'T', 'S', 'T', 'AW1', 'N'],
"abbott": ['AE1', 'B', 'AH0', 'T'],
"abbott's": ['AE1', 'B', 'AH0', 'T', 'S'],
"abbottstown": ['AE1', 'B', 'AH0', 'T', 'S', 'T', 'AW1', 'N'],
"abboud": ['AH0', 'B', 'UW1', 'D']
};